[build]
  builder = "nixpacks"

[deploy]
  startCommand = "npm run prisma:deploy && npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[variables]
  NODE_ENV = "production"
